apiVersion: v1
kind: Namespace
metadata:
  name: devops-ucu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-ucu
data:
  APP_NAME: "obligatorio3"
  APP_VERSION: "1.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-ucu
  labels:
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      securityContext:
        runAsNonRoot: true          # opcional pero suma a nivel Pod
      containers:
        - name: backend
          image: registry.konoba.space/viajes:v1
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532        # UID del usuario nonroot de distroless
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: devops-ucu
  labels:
    app.kubernetes.io/name: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
