apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: devops-ucu
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "backend.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
